### CARGAR DATOS

In [280]:
#Extraer archivos de datos .ZIP
import zipfile as zf

ArchivoZIP = "Tesis/Datos/Paciente_ID_cristian.zip"
ArchivoDES = 'Tesis/Datos/'
files = zf.ZipFile(ArchivoZIP, 'r')
files.extractall(ArchivoDES)
files.close()

In [281]:
!rm {ArchivoZIP}

In [37]:
import pandas as pd
import seaborn as sns
import numpy as np

In [282]:
!ls 'Tesis/Datos/'

Paciente_ID_001  Paciente_ID_004  Paciente_ID_007  Paciente_ID_777
Paciente_ID_002  Paciente_ID_005  Paciente_ID_008  Paciente_ID_cristian
Paciente_ID_003  Paciente_ID_006  Paciente_ID_009


In [286]:
from glob import glob
my_dirs2 = glob("/home/nrdaza/work/home/Tesis/Datos/*/")
my_dirs2.sort()
my_dirs2

['/home/nrdaza/work/home/Tesis/Datos/Paciente_ID_001/',
 '/home/nrdaza/work/home/Tesis/Datos/Paciente_ID_002/',
 '/home/nrdaza/work/home/Tesis/Datos/Paciente_ID_003/',
 '/home/nrdaza/work/home/Tesis/Datos/Paciente_ID_004/',
 '/home/nrdaza/work/home/Tesis/Datos/Paciente_ID_005/',
 '/home/nrdaza/work/home/Tesis/Datos/Paciente_ID_006/',
 '/home/nrdaza/work/home/Tesis/Datos/Paciente_ID_007/',
 '/home/nrdaza/work/home/Tesis/Datos/Paciente_ID_008/',
 '/home/nrdaza/work/home/Tesis/Datos/Paciente_ID_009/',
 '/home/nrdaza/work/home/Tesis/Datos/Paciente_ID_777/',
 '/home/nrdaza/work/home/Tesis/Datos/Paciente_ID_cristian/']

In [ ]:
# OZ, OD, Cejas, Mandibula, nada 
dict_gestos = ['Gesto_1','Gesto_2','Gesto_3','Gesto_4','Gesto_5'] 


In [84]:
# dict_datos = ['datos_1.csv','datos_2.csv','datos_3.csv','datos_4.csv','datos_5.csv','datos_6.csv', 'datos_7.csv', 'datos_8.csv', 'datos_9.csv', 'datos_10.csv']
dict_datos = glob("/home/nrdaza/work/home/Tesis/Datos/Paciente_ID_777/Gesto_1/Datos_CSV_ULTRACORTEX/*")
dict_datos.sort()
dict_datos
datos = []
for i in range(len(dict_datos)):
    datos.append(f'datos_{i+1}.csv')

['datos_1.csv',
 'datos_2.csv',
 'datos_3.csv',
 'datos_4.csv',
 'datos_5.csv',
 'datos_6.csv',
 'datos_7.csv',
 'datos_8.csv',
 'datos_9.csv',
 'datos_10.csv',
 'datos_11.csv',
 'datos_12.csv',
 'datos_13.csv',
 'datos_14.csv',
 'datos_15.csv',
 'datos_16.csv',
 'datos_17.csv',
 'datos_18.csv',
 'datos_19.csv',
 'datos_20.csv',
 'datos_21.csv',
 'datos_22.csv',
 'datos_23.csv',
 'datos_24.csv',
 'datos_25.csv',
 'datos_26.csv',
 'datos_27.csv',
 'datos_28.csv',
 'datos_29.csv',
 'datos_30.csv']

In [290]:
def Verificar_datos(my_dirs2, dict_gestos, datos):
    shapes=[]
#     for i in range(len(my_dirs2)):
    for j in range(len(dict_gestos)):
            #print(my_dirs2[i]+dict_gestos[j])
            for k in range(len(datos)):
              #print(my_dirs2[i]+dict_gestos[j]+'/Datos_CSV_MYO/'+dict_datos[k])
              df = pd.read_csv(my_dirs2[10]+dict_gestos[j]+'/Datos_CSV_ULTRACORTEX/'+datos[k],encoding='ISO-8859-1', skiprows = 2,sep=';')
              shapes.append(df.shape)
              #print(i,j,df.shape)
    print(np.unique(shapes), len(shapes))
    
    from collections import Counter
    counter=Counter(shapes)
    print(counter)
#     i = 9
#     j = 4
#     shapess = []
#     for k in range(len(datos)):
#         df = pd.read_csv(my_dirs2[i]+dict_gestos[j]+'/Datos_CSV_ULTRACORTEX/'+datos[k],encoding='ISO-8859-1', skiprows = 2,sep=';')
#         shapess.append(df.shape)
#         np.unique(shapess), len(shapess)
#         from collections import Counter
#         counter=Counter(shapess)
#         print(counter)
#         print(my_dirs2[i]+dict_gestos[j]+'/Datos_CSV_ULTRACORTEX/'+datos[k])

In [291]:

Verificar_datos(my_dirs2, dict_gestos, datos[0:20])

[ 17 622 625] 100
Counter({(625, 17): 90, (622, 17): 10})


In [222]:
features=[]
# for i in range(len(my_dirs2)):
for j in range(len(dict_gestos)):
    #print(my_dirs2[i]+dict_gestos[j])
    for k in range(len(datos)):
      #print(my_dirs2[i]+dict_gestos[j]+'/Datos_CSV_MYO/'+dict_datos[k])
      df = pd.read_csv(my_dirs2[9]+dict_gestos[j]+'/Datos_CSV_ULTRACORTEX/'+datos[k],encoding='ISO-8859-1', skiprows = 2,sep=';')
      if (df.shape[0] != 625):
            tamaño = df.shape[0]
            for i in range(625-df.shape[0]):
                df.loc[df.shape[0]+i+1] = df.values[tamaño-1-i]
      features.append(df.iloc[0:625,0:16].values)


1 150 (625, 16)
2 150 (625, 16)
3 150 (625, 16)
4 150 (625, 16)
5 150 (625, 16)
6 150 (625, 16)
7 150 (625, 16)
8 150 (625, 16)
9 150 (625, 16)
10 150 (625, 16)
11 150 (625, 16)
12 150 (625, 16)
13 150 (625, 16)
14 150 (625, 16)
15 150 (625, 16)
16 150 (625, 16)
17 150 (625, 16)
18 150 (625, 16)
19 150 (625, 16)
20 150 (625, 16)
21 150 (625, 16)
22 150 (625, 16)
23 150 (625, 16)
24 150 (625, 16)
25 150 (625, 16)
26 150 (625, 16)
27 150 (625, 16)
28 150 (625, 16)
29 150 (625, 16)
30 150 (625, 16)
31 150 (625, 16)
32 150 (625, 16)
33 150 (625, 16)
34 150 (625, 16)
35 150 (625, 16)
36 150 (625, 16)
37 150 (625, 16)
38 150 (625, 16)
39 150 (625, 16)
40 150 (625, 16)
41 150 (625, 16)
42 150 (625, 16)
43 150 (625, 16)
44 150 (625, 16)
45 150 (625, 16)
46 150 (625, 16)
47 150 (625, 16)
48 150 (625, 16)
49 150 (625, 16)
50 150 (625, 16)
51 150 (625, 16)
52 150 (625, 16)
53 150 (625, 16)
54 150 (625, 16)
55 150 (625, 16)
56 150 (625, 16)
57 150 (625, 16)
58 150 (625, 16)
59 150 (625, 16)
60 150

In [ ]:
for i in range(150):    
    len(features), features[i].shape
    if (features[i].shape == (625,16)):
        print(i+1,len(features), features[i].shape)

In [224]:
len(features), features[0].shape

(150, (625, 16))

In [225]:
features_array = np.array(features)
features_array.shape

(150, 625, 16)

In [227]:
features_array[10]

### VECTOR DE ETIQUETAS

In [245]:
#Haciendo nuestro vector de etiquetas
long = len(dict_datos)
labels = np.concatenate((np.zeros(long),np.ones(long),np.ones(long)*2,np.ones(long)*3,np.ones(long)*4),axis=0)
labels

def repeat(arr, count):
    return np.stack([arr for _ in range(count)], axis=0)

# labels = repeat(labels,len(my_dirs2)) # Cantidad de pacientes
labels = repeat(labels,1)

labels.shape


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [248]:
labels = np.reshape(labels,150)
labels, labels.shape

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2., 2., 2., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
        4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]),
 (150,))

### AJUSTE DE TENSOR DE ENTRADA 

In [252]:
features_array.shape, np.sum(features_array[0:150,:,:])

((150, 625, 16), -16253.944912877403)

In [254]:
features_array2 = np.reshape(features_array,(150,10000))
features_array2.shape, np.sum(features_array2[0:150,:])

((150, 10000), -16253.944912877403)

In [284]:
Xsplit = int(features_array2.shape[0] * 0.8) 
X_train_split = features_array2[0:Xsplit,:]
X_test_split = features_array2[Xsplit:,:]
labels_train = labels[0:Xsplit]
labels_test = labels[Xsplit:]


In [285]:
print("Label distribution: {}, total classes {}".format(np.unique(labels_train), len(np.unique(labels_train))))

Label distribution: [0. 1. 2. 3.], total classes 4
